import Head from "next/head";
import styles from "@/styles/home/Home.module.css";
import BlogBlock from "@/src/components/template/BlogBlock";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" width="100px" height="30px" />
        <title>Blogospot</title>
      </Head>
      <main className={styles.main}>
        <div className={styles.hero}></div>
        <div className="container w-full mx-auto py-9 px-5">
          <h1 className={styles.container_h1}>Featured Post</h1>
          <BlogBlock data={data} />
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { data } = await import("/data/data.json");
  return {
    props: {
      data,
    },
  };
}
// import React, { useState } from 'react';

// const Pagination = ({ itemsPerPage, totalItems, paginate }) => {
//   const pageNumbers = [];

//   // Calculate the number of pages
//   for (let i = 1; i <= Math.ceil(totalItems / itemsPerPage); i++) {
//     pageNumbers.push(i);
//   }

//   // Set the current page to 1
//   const [currentPage, setCurrentPage] = useState(1);

//   // Get the index of the last item on the current page
//   const indexOfLastItem = currentPage * itemsPerPage;
//   // Get the index of the first item on the current page
//   const indexOfFirstItem = indexOfLastItem - itemsPerPage;
//   // Get the current items
//   const currentItems = items.slice(indexOfFirstItem, indexOfLastItem);

//   const handleClick = (pageNumber) => {
//     setCurrentPage(pageNumber);
//     paginate(pageNumber);
//   };

//   return (
//     <nav>
//       <ul className='pagination'>
//         {pageNumbers.map((number) => (
//           <li key={number} className='page-item'>
//             <a
//               onClick={() => handleClick(number)}
//               href='!#'
//               className='page-link'
//             >
//               {number}
//             </a>
//           </li>
//         ))}
//       </ul>
//     </nav>
//   );
// };

// export default Pagination;