import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/home/Home.module.css";
import BlogBlock from "@/src/components/template/BlogBlock";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" width="100px" height="30px" />
        <title>Blogospot</title>
      </Head>
      <main className={styles.main}>
        <div className={styles.hero}></div>
        <div className="container w-full mx-auto py-9 px-5">
          <h1 className={styles.container_h1}>Featured Post</h1>
          <BlogBlock data={data} />
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { data } = await import("/data/data.json");
  return {
    props: {
      data,
    },
  };
}
