import Head from "next/head";
import styles from "@/styles/home/Home.module.css";
import BlogBlock from "@/src/components/template/BlogBlock";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" width="100px" height="30px" />
        <title>Blogospot</title>
      </Head>
      <main className="bg-[#f5f5f5]">
        <div className={styles.hero}></div>
        <div className="container m-auto flex flex-col md:flex-row-reverse justify-content-between mt-11 relative">
          <div className={`${styles.main} md:w-8/12`}>
            <h1 className={styles.container_h1}>Featured Post</h1>
            <BlogBlock data={data} />
          </div>
          <div className="md:w-4/12 h-screen bg-[#a8201a] md:mr-6 rounded-lg hover:bg-[#000] transition-all ease-in-out delay-150"></div>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { data } = await import("/data/data.json");
  return {
    props: {
      data,
    },
  };
}
